name: Sync READMEs

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  sync-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy READMEs
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/sri0606/BrainWaiveApp.git temp/brainwaive
          cp temp/brainwaive/README.md README/brainwaive.md
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/sri0606/EMAIL_List.git temp/email_list
          cp temp/email_list/README.md README/email_list.md
          # Repeat for other private repositories

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'sri'
          git config --global user.email 'sri0606@users.noreply.github.com'
          git commit -am "Sync ReadMe's"
          git push